
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 500
PLAYER_SPEED = 400
PLAYER_SHOT_SPEED = 600
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.1

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.6
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5

