
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

__all__ = [
    "SCREEN_HEIGHT", 
    "SCREEN_WIDTH", 
    "PLAYER_RADIUS",
    "PLAYER_SPEED",
    "PLAYER_TURN_SPEED",
    "LINE_WIDTH",
    "ASTEROID_KINDS",
    "ASTEROID_MIN_RADIUS",
    "ASTEROID_MAX_RADIUS",
    "ASTEROID_SPAWN_RATE_SECONDS"
]
